export const challenges = [
    { id: 'c_1', type: 'statement', packs: ['classic'], spiciness: 1, points: 2, text: 'Players wearing glasses take a sip.' },
    { id: 'c_2', type: 'statement', packs: ['classic'], spiciness: 1, points: 1, text: 'The floor is lava! Last one to stand on a chair drinks.' },
    { id: 'c_3', type: 'statement', packs: ['classic'], spiciness: 1, points: 1, text: 'Everyone touch your nose! Last one drinks.' },
    { id: 'c_4', type: 'statement', packs: ['classic'], spiciness: 2, points: 2, text: 'Medusa: Everyone look down. On 3, look up at someone. If you lock eyes, cheers!' },
    { id: 'c_5', type: 'virus', packs: ['classic'], spiciness: 2, points: 3, text: 'VIRUS: You are the "Thumb Master". Whenever you place your thumb on the table, everyone else must too.' },
    { id: 'c_6', type: 'virus', packs: ['classic'], spiciness: 2, points: 3, text: "VIRUS: You can no longer say 'Yes' or 'No'. Penalty: 1 Sip." },
    { id: 'c_7', type: 'virus', packs: ['classic'], spiciness: 2, points: 3, text: "VIRUS: You must end every sentence with 'Daddy'. Penalty: 1 Sip." },
    { id: 'c_8', type: 'virus', packs: ['classic'], spiciness: 2, points: 3, text: "VIRUS: Little Green Man. Remove an imaginary man from your drink before sipping, or drink twice." },
    { id: 'c_9', type: 'virus', packs: ['classic'], spiciness: 3, points: 3, text: "VIRUS: T-Rex Arms. Keep your elbows touching your ribs." },
    { id: 'c_10', type: 'virus', packs: ['classic'], spiciness: 2, points: 3, text: "VIRUS: Foreigner. You must speak in a fake accent." },
    { id: 'c_11', type: 'standard', packs: ['classic'], spiciness: 1, points: 1, text: "Drinks if you are shorter than the person to your right." },
    { id: 'c_12', type: 'standard', packs: ['classic'], spiciness: 1, points: 2, text: "The tallest player gives out 2 sips." },
    { id: 'c_13', type: 'standard', packs: ['classic'], spiciness: 2, points: 2, text: "Rock, Paper, Scissors with person on left. Loser drinks." },
    { id: 'c_14', type: 'standard', packs: ['classic'], spiciness: 3, points: 5, text: "Waterfall! Choose a direction." },
    { id: 'c_15', type: 'standard', packs: ['classic'], spiciness: 2, points: 2, text: "Sky's the limit! Last one to point up drinks." },
    { id: 'c_16', type: 'standard', packs: ['classic'], spiciness: 1, points: 1, text: "Selfie time: Take a group selfie. Best pose gives 2 sips." },
    { id: 'b_1', type: 'bomb', packs: ['bomb', 'classic'], spiciness: 1, points: 2, duration: 10, text: 'Name 3 Car Brands' },
    { id: 'b_2', type: 'bomb', packs: ['bomb', 'classic'], spiciness: 1, points: 2, duration: 12, text: 'Name 3 Countries in Europe' },
    { id: 'b_3', type: 'bomb', packs: ['bomb', 'classic'], spiciness: 2, points: 2, duration: 10, text: 'Rhyme with "Drink"' },
    { id: 'b_4', type: 'bomb', packs: ['bomb'], spiciness: 2, points: 3, duration: 15, text: 'Name 3 Romantic Activities' },
    { id: 'b_5', type: 'bomb', packs: ['bomb'], spiciness: 1, points: 2, duration: 12, text: 'Name 3 Harry Potter Characters' },
    { id: 'b_6', type: 'bomb', packs: ['bomb', 'classic'], spiciness: 2, points: 2, duration: 10, text: 'Name 3 Pizza Toppings' },
    { id: 'v_1', type: 'vote', packs: ['vote', 'mostLikely', 'classic'], spiciness: 2, points: 2, text: 'Who is most likely to get arrested?' },
    { id: 'v_2', type: 'vote', packs: ['vote', 'mostLikely'], spiciness: 2, points: 2, text: 'Who is the best kisser?' },
    { id: 'v_3', type: 'vote', packs: ['vote', 'mostLikely'], spiciness: 1, points: 2, text: 'Who will get sick first tonight?' },
    { id: 'v_4', type: 'vote', packs: ['vote', 'mostLikely'], spiciness: 1, points: 2, text: 'Who has the worst taste in music?' },
    { id: 'v_5', type: 'vote', packs: ['vote', 'mostLikely', 'classic'], spiciness: 3, points: 2, text: 'Who would survive a zombie apocalypse?' },
    { id: 'v_6', type: 'vote', packs: ['vote', 'mostLikely'], spiciness: 3, points: 2, text: "Who is most likely to have a secret family?" },
    { id: 'v_7', type: 'vote', packs: ['vote', 'mostLikely'], spiciness: 1, points: 2, text: "Who is most likely to appear on a reality dating show?" },
    { id: 'v_8', type: 'vote', packs: ['vote', 'mostLikely'], spiciness: 3, points: 2, text: "Who is most likely to hook up with an ex tonight?" },
    { id: 'v_9', type: 'vote', packs: ['vote', 'mostLikely'], spiciness: 2, points: 2, text: "Who is most likely to vomit tonight?" },
    { id: 'v_10', type: 'vote', packs: ['vote', 'mostLikely'], spiciness: 3, points: 2, text: "Who uses the most filter on photos?" },
    { id: 'ch_1', type: 'charade', packs: ['charade', 'classic'], spiciness: 1, points: 2, text: 'Act out: A T-Rex making a bed.' },
    { id: 'ch_2', type: 'charade', packs: ['charade', 'classic'], spiciness: 2, points: 2, text: 'Act out: Your boss drunk.' },
    { id: 'ch_3', type: 'charade', packs: ['charade'], spiciness: 3, points: 2, text: 'Act out: A stripper pole malfunction.' },
    { id: 'ch_4', type: 'charade', packs: ['charade'], spiciness: 1, points: 2, text: 'Act out: Giving birth to a watermelon.' },
    { id: 'ch_5', type: 'charade', packs: ['charade'], spiciness: 2, points: 2, text: 'Act out: Elon Musk buying Twitter.' },
    { id: 'nhie_1', type: 'neverHaveIEver', packs: ['neverHaveIEver', 'classic'], spiciness: 2, points: 1, text: 'Never have I ever been arrested.' },
    { id: 'nhie_2', type: 'neverHaveIEver', packs: ['neverHaveIEver', 'classic'], spiciness: 1, points: 1, text: 'Never have I ever cheated on a test.' },
    { id: 'nhie_3', type: 'neverHaveIEver', packs: ['neverHaveIEver'], spiciness: 3, points: 1, text: 'Never have I ever sent a nude.' },
    { id: 'nhie_4', type: 'neverHaveIEver', packs: ['neverHaveIEver'], spiciness: 2, points: 1, text: 'Never have I ever ghosted someone.' },
    { id: 'nhie_5', type: 'neverHaveIEver', packs: ['neverHaveIEver'], spiciness: 1, points: 1, text: 'Never have I ever pretended to be sick to skip work.' },
    { id: 'nhie_6', type: 'neverHaveIEver', packs: ['neverHaveIEver'], spiciness: 3, points: 1, text: "Never have I ever hooked up in a car." },
    { id: 'nhie_7', type: 'neverHaveIEver', packs: ['neverHaveIEver'], spiciness: 5, points: 1, text: "Never have I ever sent a nude to the wrong person." },
    { id: 'nhie_8', type: 'neverHaveIEver', packs: ['neverHaveIEver'], spiciness: 4, points: 1, text: "Never have I ever hooked up with a friend's ex." },
    { id: 'wyr_1', type: 'wouldYouRather', packs: ['wouldYouRather', 'classic'], spiciness: 1, points: 0, text: 'Lose all your hair OR lose all your teeth?' },
    { id: 'wyr_2', type: 'wouldYouRather', packs: ['wouldYouRather', 'classic'], spiciness: 1, points: 0, text: 'Be super fast OR be super strong?' },
    { id: 'wyr_3', type: 'wouldYouRather', packs: ['wouldYouRather'], spiciness: 2, points: 0, text: 'Always say everything on your mind OR never be able to speak again?' },
    { id: 'wyr_4', type: 'wouldYouRather', packs: ['wouldYouRather'], spiciness: 3, points: 0, text: 'Date your best friend\'s ex OR date your ex\'s best friend?' },
    { id: 'tab_1', type: 'taboo', packs: ['taboo', 'classic'], spiciness: 1, points: 3, word: 'Party', forbidden: ['Celebration', 'Fun', 'Music', 'Guests'] },
    { id: 'tab_2', type: 'taboo', packs: ['taboo'], spiciness: 2, points: 3, word: 'Alcohol', forbidden: ['Drink', 'Beer', 'Wine', 'Drunk'] },
    { id: 'tab_3', type: 'taboo', packs: ['taboo', 'classic'], spiciness: 2, points: 3, word: 'Instagram', forbidden: ['Photo', 'App', 'Influencer', 'Like'] },
    { id: 'tab_4', type: 'taboo', packs: ['taboo'], spiciness: 3, points: 3, word: 'Sex', forbidden: ['Bed', 'Love', 'Gender', 'Making'] },
    { id: 'para_1', type: 'paranoia', packs: ['paranoia', 'classic'], spiciness: 2, points: 2, translationKey: 'para_1', question: 'Who here secretly hates everyone?' },
    { id: 'para_2', type: 'paranoia', packs: ['paranoia'], spiciness: 3, points: 2, translationKey: 'para_2', question: 'Who has the best body?' },
    { id: 'para_3', type: 'paranoia', packs: ['paranoia'], spiciness: 1, points: 2, translationKey: 'para_3', question: 'Who is most likely to become a millionaire?' },
    { id: 'para_4', type: 'paranoia', packs: ['paranoia'], spiciness: 4, points: 2, translationKey: 'para_4', question: 'Who would you sleep with if you had to?' },
    { id: 'para_5', type: 'paranoia', packs: ['paranoia'], spiciness: 3, points: 2, translationKey: 'para_5', question: "Whose voice is the most annoying?" },
    { id: 'para_6', type: 'paranoia', packs: ['paranoia'], spiciness: 5, points: 2, translationKey: 'para_6', question: "Who do you think is bad in bed?" },
    { id: 'tod_1', type: 'truth', packs: ['truthOrDare', 'tod', 'classic'], spiciness: 2, points: 1, text: 'What is the biggest lie you have ever told?' },
    { id: 'tod_2', type: 'truth', packs: ['truthOrDare', 'tod'], spiciness: 3, points: 1, text: 'Who in this room would you date?' },
    { id: 'tod_3', type: 'dare', packs: ['truthOrDare', 'tod', 'classic'], spiciness: 2, points: 2, text: 'Do 10 pushups immediately.' },
    { id: 'tod_4', type: 'dare', packs: ['truthOrDare', 'tod'], spiciness: 3, points: 3, text: 'Let the group DM someone from your phone.' },
    { id: 'tod_5', type: 'dare', packs: ['truthOrDare', 'tod'], spiciness: 2, points: 2, text: 'Show the last photo in your gallery.' },
    { id: 'tod_6', type: 'dare', packs: ['truthOrDare', 'tod'], spiciness: 4, points: 3, text: "Post an embarrassing photo on your Story." },
    { id: 'tod_7', type: 'truth', packs: ['truthOrDare', 'tod'], spiciness: 5, points: 3, text: "Have you ever cheated?" },
    { id: 'tod_8', type: 'truth', packs: ['truthOrDare', 'tod'], spiciness: 3, points: 2, text: "What's the weirdest dream you've had about someone here?" },
    { id: 'mkk_1', type: 'vote', packs: ['marryKissKill', 'classic'], spiciness: 2, points: 2, translationKey: 'mkk_1', text: 'Kiss, Marry, Kill: The person on your left, right, and opposite.' },
    { id: 'mkk_2', type: 'vote', packs: ['marryKissKill'], spiciness: 1, points: 2, translationKey: 'mkk_2', text: 'Kiss, Marry, Kill: Batman, Superman, Spiderman.' },
    { id: 'mkk_3', type: 'vote', packs: ['marryKissKill'], spiciness: 3, points: 2, translationKey: 'mkk_3', text: 'TWIST! Date, Marry, Ghost: Your Ex, Your Boss, Your Neighbor.' },
    { id: 'mkk_4', type: 'vote', packs: ['marryKissKill'], spiciness: 2, points: 2, translationKey: 'mkk_4', text: 'Kiss, Marry, Kill: Rihanna, Beyoncé, Taylor Swift.' },
    { id: 'mkk_5', type: 'vote', packs: ['marryKissKill'], spiciness: 2, points: 2, translationKey: 'mkk_5', text: 'TWIST! Kiss, Slap, Hug: The 3 people closest to you.' },
    { id: 'mkk_6', type: 'vote', packs: ['marryKissKill'], spiciness: 1, points: 2, translationKey: 'mkk_6', text: 'TWIST! Block, Report, Subscribe: Elon Musk, Mark Zuckerberg, Jeff Bezos.' },
    { id: 'mm_1', type: 'statement', packs: ['mindMatch', 'classic'], spiciness: 1, points: 2, translationKey: 'mm_1', text: 'Mind Match! Only pairs win. On 3, describe the person to your left with ONE word.' },
    { id: 'mm_2', type: 'statement', packs: ['mindMatch'], spiciness: 1, points: 2, translationKey: 'mm_2', text: 'Mind Match! On 3, everyone say a Brand of Car. Matches drink!' },
    { id: 'mm_3', type: 'statement', packs: ['mindMatch'], spiciness: 1, points: 2, translationKey: 'mm_3', text: 'Mind Match! On 3, everyone say a Fruit. Matches share a sip!' },
    { id: 'mm_4', type: 'statement', packs: ['mindMatch'], spiciness: 2, points: 2, translationKey: 'mm_4', text: 'Mind Match! On 3, point to the person most likely to blackout tonight. Consensus drinks!' },
    { id: 'wa_1', type: 'statement', packs: ['wrongAnswers', 'classic'], spiciness: 1, points: 2, translationKey: 'wa_1', text: 'Wrong Answers Only! Point at someone and ask: "What are clouds made of?" Anyone who laughs drinks.' },
    { id: 'wa_2', type: 'statement', packs: ['wrongAnswers'], spiciness: 1, points: 2, translationKey: 'wa_2', text: 'Wrong Answers Only! Speed Round: Explain how babies are made in 5 seconds.' },
    { id: 'wa_3', type: 'statement', packs: ['wrongAnswers'], spiciness: 2, points: 2, translationKey: 'wa_3', text: 'Wrong Answers Only! What is the capital of France? (If they say Paris, they finish their drink).' },
    { id: 'wa_4', type: 'statement', packs: ['wrongAnswers'], spiciness: 1, points: 2, translationKey: 'wa_4', text: 'Wrong Answers Only! Describe your job.' },
    { id: '1010_1', type: 'vote', packs: ['tenOuttaTen', 'classic'], spiciness: 2, points: 2, translationKey: '1010_1', text: 'They are a 10/10 but... they clap when the plane lands. New rating?' },
    { id: '1010_2', type: 'vote', packs: ['tenOuttaTen'], spiciness: 2, points: 2, translationKey: '1010_2', text: 'They are a 10/10 but... they refer to themselves in the third person. New rating?' },
    { id: '1010_3', type: 'vote', packs: ['tenOuttaTen'], spiciness: 3, points: 2, translationKey: '1010_3', text: 'They are a 10/10 but... they are still friends with all their exes. New rating?' },
    { id: '1010_4', type: 'vote', packs: ['tenOuttaTen'], spiciness: 1, points: 2, translationKey: '1010_4', text: 'They are a 10/10 but... they wear socks with sandals. New rating?' },
    { id: 'hyp_1', type: 'vote', packs: ['hypotheticals', 'classic'], spiciness: 2, points: 2, translationKey: 'hyp_1', text: 'Hypothetically: If you found a wallet with $1000 and an ID, would you return it?' },
    { id: 'hyp_2', type: 'vote', packs: ['hypotheticals'], spiciness: 3, points: 2, translationKey: 'hyp_2', text: 'Hypothetically: Would you punch your best friend for $50,000? (They don\'t know why).' },
    { id: 'hyp_3', type: 'vote', packs: ['hypotheticals'], spiciness: 2, points: 2, translationKey: 'hyp_3', text: 'Hypothetically: You can only eat one food for the rest of your life. Pizza or Tacos?' },
    { id: 'hyp_4', type: 'vote', packs: ['hypotheticals'], spiciness: 3, points: 2, translationKey: 'hyp_4', text: 'Hypothetically: Would you accept $10M if a snail chases you forever and kills you if it touches you?' },
    { id: 'bet_1', type: 'statement', packs: ['betBuddy', 'classic'], spiciness: 2, points: 3, translationKey: 'bet_1', text: 'Bet Buddy! I bet that {{p_left}} cannot name 5 capitals in 10 seconds. Loser drinks.' },
    { id: 'bet_2', type: 'statement', packs: ['betBuddy'], spiciness: 2, points: 3, translationKey: 'bet_2', text: 'Bet Buddy! I bet that {{p_right}} can touch their nose with their tongue. If they fail, they drink.' },
    { id: 'bet_3', type: 'statement', packs: ['betBuddy'], spiciness: 3, points: 3, translationKey: 'bet_3', text: 'Bet Buddy! Pick a target. Bet them they can\'t do 20 pushups. Stakes: 3 sips.' },
    { id: 'fake_1', type: 'statement', packs: ['fakeOrFact', 'classic'], spiciness: 1, points: 2, translationKey: 'fake_1', text: 'Fake or Fact? Raccoons can rotate their hind feet 180 degrees. (Answer: FACT! This helps them climb down trees headfirst).' },
    { id: 'fake_2', type: 'statement', packs: ['fakeOrFact'], spiciness: 1, points: 2, translationKey: 'fake_2', text: 'Fake or Fact? Humans share 50% of their DNA with bananas. (Answer: FACT!)' },
    { id: 'fake_3', type: 'statement', packs: ['fakeOrFact'], spiciness: 2, points: 2, translationKey: 'fake_3', text: 'Fake or Fact? Napoleon was short. (Answer: FAKE! He was average height for the time).' },
    { id: 'fake_4', type: 'statement', packs: ['fakeOrFact'], spiciness: 1, points: 2, translationKey: 'fake_4', text: 'Fake or Fact? Goldfish have a 3-second memory. (Answer: FAKE! They can remember for months).' },
    { id: 'prin_1', type: 'statement', packs: ['princess'], spiciness: 1, points: 1, translationKey: 'prin_1', text: 'Debate: He opens the car door for you. Standard or Princess?' },
    { id: 'prin_2', type: 'statement', packs: ['princess'], spiciness: 1, points: 1, translationKey: 'prin_2', text: 'Debate: He pays for the entire dinner on the first date. Standard or Princess?' },
    { id: 'prin_3', type: 'statement', packs: ['princess'], spiciness: 2, points: 1, translationKey: 'prin_3', text: 'Debate: He buys you flowers for no reason. Standard or Princess?' },
    { id: 'prin_4', type: 'statement', packs: ['princess'], spiciness: 2, points: 1, translationKey: 'prin_4', text: 'Debate: He ties your shoelaces in public. Standard or Princess?' },
    { id: 'prin_5', type: 'statement', packs: ['princess'], spiciness: 1, points: 1, translationKey: 'prin_5', text: 'Debate: He texts you "Good Morning" every single day. Standard or Princess?' },

    // -- Themes --
    { id: 'hall_1', type: 'charade', packs: ['halloween'], spiciness: 1, points: 2, translationKey: 'hall_1', text: 'Act out: A Zombie eating brains.' },
    { id: 'hall_2', type: 'statement', packs: ['halloween'], spiciness: 1, points: 2, translationKey: 'hall_2', text: 'Vampire Mode: You cannot show your teeth when you laugh for one round.' },
    { id: 'xmas_1', type: 'statement', packs: ['christmas'], spiciness: 1, points: 1, translationKey: 'xmas_1', text: 'Everyone wearing RED takes a sip (Santa style).' },
    { id: 'xmas_2', type: 'statement', packs: ['christmas'], spiciness: 1, points: 1, translationKey: 'xmas_2', text: 'Everyone who has already bought all their gifts gives 2 sips. Planners!' },
    { id: 'xmas_3', type: 'statement', packs: ['christmas'], spiciness: 2, points: 1, translationKey: 'xmas_3', text: 'Everyone single this Christmas takes a shot. (Cheers to freedom!).' },
    { id: 'xmas_4', type: 'statement', packs: ['christmas'], spiciness: 1, points: 1, translationKey: 'xmas_4', text: 'Last person to sing "Jingle Bells" drinks.' },
    { id: 'xmas_5', type: 'charade', packs: ['christmas'], spiciness: 1, points: 2, translationKey: 'xmas_5', text: 'Act out: Santa getting stuck in a chimney.' },
    { id: 'xmas_6', type: 'charade', packs: ['christmas'], spiciness: 2, points: 2, translationKey: 'xmas_6', text: 'Act out: A Reindeer flying while drunk.' },
    { id: 'xmas_7', type: 'charade', packs: ['christmas'], spiciness: 2, points: 2, translationKey: 'xmas_7', text: 'Act out: Wrapping a weirdly shaped gift.' },
    { id: 'xmas_8', type: 'truth', packs: ['christmas'], spiciness: 2, points: 2, translationKey: 'xmas_8', text: 'What is the worst gift you have ever received?' },
    { id: 'xmas_9', type: 'truth', packs: ['christmas'], spiciness: 2, points: 2, translationKey: 'xmas_9', text: 'Have you ever re-gifted a present? To whom?' },
    { id: 'xmas_10', type: 'dare', packs: ['christmas'], spiciness: 2, points: 3, text: 'Sit on the lap of the person to your right and tell them what you want for Christmas.' },
    { id: 'xmas_11', type: 'dare', packs: ['christmas'], spiciness: 1, points: 3, text: 'Sing the chorus of "All I Want For Christmas Is You" as loud as you can.' },
    { id: 'xmas_12', type: 'vote', packs: ['christmas'], spiciness: 1, points: 2, text: 'Who is most likely to get Coal this year? (Naughty List).' },
    { id: 'xmas_13', type: 'vote', packs: ['christmas'], spiciness: 2, points: 2, text: 'Who is most likely to get drunk at a family dinner?' },
    { id: 'xmas_14', type: 'neverHaveIEver', packs: ['christmas'], spiciness: 1, points: 1, text: 'Never have I ever peaked at my presents early.' },
    { id: 'xmas_15', type: 'statement', packs: ['christmas'], spiciness: 1, points: 1, text: 'Toast: Raise your glass to 2026! Everyone drinks.' },
    { id: 'xmas_16', type: 'vote', packs: ['christmas'], spiciness: 1, points: 2, text: 'Who hates Christmas music the most?' },
    { id: 'xmas_17', type: 'charade', packs: ['christmas'], spiciness: 1, points: 2, text: 'Act out: Building a snowman.' },
    { id: 'xmas_18', type: 'statement', packs: ['christmas'], spiciness: 1, points: 2, text: 'Fake or Fact? Jingle Bells was originally a Thanksgiving song. (Fact!).' },
    { id: 'mg_bomb_1', type: 'bomb', packs: ['bomb', 'classic'], text: "BOMB PARTY: Word Bomb", bombMode: 'classic', spiciness: 2 },
    { id: 'mg_bomb_2', type: 'bomb', packs: ['bomb'], text: "BOMB PARTY: 5 Second Panic", bombMode: 'panic', spiciness: 3 },
    { id: 'mg_bomb_3', type: 'bomb', packs: ['bomb'], text: "BOMB PARTY: Alphabet Soup", bombMode: 'alphabet', spiciness: 2 },
    { id: 'mg_charades_1', type: 'charades', packs: ['charades'], text: "HEADS UP: Charades round!", spiciness: 1 },
    { id: 'mg_spy_1', type: 'spy', packs: ['spy', 'classic'], text: "IMPOSTOR: Find the liar!", spiciness: 2 },

    // Fake Artist
    { id: 'mg_art_1', type: 'fakeArtist', packs: ['fakeArtist', 'classic'], text: "DOODLE DRAMA: Who is the fake artist?", spiciness: 2 },
    { id: 'mg_sec_1', type: 'secrets', packs: ['secrets', 'classic'], translationKey: "secrets_sec_fear", spiciness: 2 },
    { id: 'mg_sec_2', type: 'secrets', packs: ['secrets'], translationKey: "secrets_sec_hottest", spiciness: 3 },
    { id: 'mg_sec_3', type: 'secrets', packs: ['secrets'], translationKey: "secrets_sec_worst", spiciness: 3 },
    { id: 'mg_dt_1', type: 'darkTales', packs: ['darkTales', 'classic'], translationKey: "dt_albatross", spiciness: 3 },
    { id: 'mg_dt_2', type: 'darkTales', packs: ['darkTales', 'classic'], translationKey: "dt_shoes", spiciness: 3 },
    { id: 'hot_1', type: 'standard', packs: ['taboo', 'hot', 'closeFriends'], text: "Moan as loud as you can.", spiciness: 4 },
    { id: 'hot_2', type: 'standard', packs: ['taboo', 'hot', 'closeFriends'], text: "Take off one item of clothing.", spiciness: 4 },
    { id: 'hot_3', type: 'standard', packs: ['taboo', 'hot', 'closeFriends'], text: "Give the person to your right a lap dance.", spiciness: 5 },
    { id: 'hot_4', type: 'standard', packs: ['taboo', 'hot', 'closeFriends'], text: "Kiss the person you think is the hottest.", spiciness: 5 },
    { id: 'hot_5', type: 'standard', packs: ['taboo', 'hot', 'closeFriends'], text: "Let the group decide a text to send to your ex.", spiciness: 6 },
    { id: 'hot_6', type: 'standard', packs: ['taboo', 'hot', 'closeFriends'], text: "Show your last received nude (or drink 5 times).", spiciness: 6 },
    { id: 'hot_7', type: 'standard', packs: ['taboo', 'hot', 'closeFriends'], text: "Demonstrate your favorite sex position with a pillow.", spiciness: 5 },
    { id: 'hot_8', type: 'standard', packs: ['taboo', 'hot', 'closeFriends'], text: "Let someone bite your neck.", spiciness: 5 },
    { id: 'hot_9', type: 'standard', packs: ['taboo', 'hot', 'closeFriends'], text: "Whisper something dirty to the person on your left.", spiciness: 4 },
    { id: 'hot_10', type: 'standard', packs: ['taboo', 'hot', 'closeFriends'], text: "Blindfold yourself and guess who kisses you.", spiciness: 6 },
    { id: 'r_1', type: 'reflex', packs: ['classic'], text: "TAP FAST!", spiciness: 2 },
    { id: 'r_2', type: 'reflex', packs: ['classic'], text: "DON'T SNEEZE, TAP!", spiciness: 2 },
    { id: 'p_1', type: 'precision', packs: ['classic'], text: "Stop the timer at exactly 5.00s", spiciness: 2 },
    { id: 's_1', type: 'shake', packs: ['classic'], text: "Shake the phone to pop the champagne!", spiciness: 1 },
];
